spring.application.name=freeflix-backend
# MongoDB
spring.data.mongodb.uri=mongodb+srv://nanuadityakumar_db_user:84fhf848f494fj9j4jj48gj@cluster0.b2hlhnt.mongodb.net/movie-app-db

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

# FreeFlix custom settings
freeflix.jwt.secret=YourSuperLongAndVerySecureSecretKey1234567890
freeflix.jwt.expirationMinutes=120

freeflix.streaming.hlsBaseUrl=http://localhost:8080/hls
freeflix.streaming.adPolicy.prerollSeconds=15
freeflix.streaming.adPolicy.midrollIntervalMinutes=20
freeflix.streaming.adPolicy.postrollSeconds=10

freeflix.licensing.mode=PUBLIC_DOMAIN
# or INDIE_PARTNERS

###mongoimport --uri "mongodb+srv://nanuadityakumar_db_user:84fhf848f494fj9j4jj48gj@cluster0.b2hlhnt.mongodb.net/" --collection movie-app-db --file [movies.json](http://_vscodecontentref_/2) --jsonArray